import { ISODate } from './';
export declare const dateToday: Date;
export declare const prettifyDate: (date: Date) => string;
export declare const prettifyDateExtended: (date: Date) => string;
export declare const prettifyDateFull: (date: Date) => string;
export declare const dateToISODate: (date: Date) => ISODate;
export declare const ISODateToDate: (isoDate: ISODate) => Date;
export declare const getISOWeekdayFromISODate: (isoDate: ISODate) => number;
export declare const getDatesInMonth: (month: Date, onlyWeekDays?: boolean) => Date[];
export declare const getLastWeekDayInMonth: (month: Date) => Date;
export declare const getFirstWeekDayInMonth: (month: Date) => Date;
export declare const isDateInDates: (date: Date, dates?: Date[] | undefined) => boolean;
export declare const dateIsWeekDay: (date: Date) => boolean;
export declare const getYearMonthKey: (date: Date) => string;
